### ISSUE TITLE
Save errors events inside the DB

### ISSUE THREAD

**Issue by guillecro** [DemocracyOS/core#22]
Save Log errors level events inside the database for prod

**Comment by guillecro** [comment]
Hey @franciclo 
I was wondering.. what kind of logs should we state per environment? What you think about this?

| Env | Logger |
| --- | --- |
| `env` | Log in files: `app.log` will log events of `info` level, `error.log` will log `error` level events, and in the database under `logs` collection all the events of `warning` level. No console logs. |
| `dev` | Logs in the console |
| `test` | No logs. Just mocha logs. |

Should the `logs` collection of the database log events in `dev` enviroment? What you think?

**Comment by franciclo** [comment]
For now we just need to persist errors always, and in dev and testing to show debug logs.

**Comment by guillecro** [comment]
Ok i will add saving logs inside the database even in dev env!
