### ISSUE TITLE
General Comments for Documents

### ISSUE THREAD

**Issue by guillecro** [DemocracyOS/core#41]
A document should have "general" comments.
A comment follows this schema:

| field | type | description |
| --- | --- | --- |
| `user` | Ref: User | The id of the user |
| `document` | Ref: Document | An ID with the reference of the document | 
| `field` | String | A reference of the document | 
| `comment` | String | The comment itself |

**Comment by franciclo** [comment]
Comments are attached to some rich text field, not the whole document.
The likes should be in a separated collection, we could skip this for now.

**Comment by guillecro** [comment]
Updated! After a call with @franciclo
