### ISSUE TITLE
Project and User API

### ISSUE THREAD

**Issue by luarar** [DemocracyOS/core#45]
In order to build the UI components, we need a Project API and a User data API. This is an example API we have been working with:
https://www.mockaroo.com/schemas/131006

The user data API has information about the logged user, such as:
Name, email, avatarImg, charge or position, etc.

Maybe you can use similar schemas we've worked with in other projects.

**Comment by guillecro** [comment]
Thats perfect Lau!
You think its safe to get ideas from the democracyOS v2 repo?
Also, can you pleaaaaaase copy and pase the data from mockaroo? cause is asking me to sign in

**Comment by luarar** [comment]
I think is safe to get an idea from DemOS structure, here you have an example JSON, and you can also watch the designer screens to get a better idea of what kind of data we need:

The designs: https://app.zeplin.io/project/5b840ee3984b4542724d420d/dashboard

An example:
`[
  {
    "id": {
      "$oid": "5bb274ccfc13ae54520003e8"
    },
    "img": "https://i.ytimg.com/vi/NPX6Oc9rgbo/maxresdefault.jpg",
    "commentaries": 92,
    "limitDate": "10/14/2017",
    "title": "varius integer ac leo pellentesque ultrices mattis odio donec",
    "tagTitle": "natoque penatibus",
    "author": {
      "name": "Monika Sutherel",
      "party": "non mi integer ac neque duis bibendum morbi non quam nec dui luctus",
      "avatarImg": "https://robohash.org/quiundeet.jpg?size=50x50&set=set1"
    },
    "version": 69,
    "createdAt": "10/9/2017"
  }
]`

**Comment by guillecro** [comment]
Closing for now!
