### ISSUE TITLE
Revisit documentation of the API

### ISSUE THREAD

**Issue by guillecro** [DemocracyOS/core#65]
There has to be a revision of the documentation, a bit delayed with the current code because of calendar issues

**Comment by renaudham** [comment]
Hi.
Please any news on this? There is mainly no info anywhere to help to see how to connect an external app to this API, what are the endpoint, data models, authentification etc..

Is there any way to create a user from an external app ? this is important for us.

Any docs also about eventuals webhooks?

thanks

**Comment by guillecro** [comment]
Hey there @renaudham

Sorry to inform you this repository is deprecated. Wasn't my decission :(

**Comment by renaudham** [comment]
Hi

Ok so where can we find informations now?

Thanks
*Renaud Hamelin*

Le mar. 19 mars 2019 à 18:47, Guillermo Croppi <notifications@github.com> a
écrit :

**Comment by guillecro** [comment]
I believe you are looking documentation for DemocracyOS, you can go to the website http://democracyos.org/ and there is a documentation about it.

Sadly, the maintainers don't work here anymore, and I am not in position to resolve any issues related to those previous projects. Sorry about the bad news.

**Comment by renaudham** [comment]
Thanks anyway

the documentation there is very very poor and therefore will block us from
using this system.

Thanks for your answers

*Renaud Hamelin*

Le mar. 19 mars 2019 à 19:13, Guillermo Croppi <notifications@github.com> a
écrit :
